"""empty message

Revision ID: 37c3308ba315
Revises:
Create Date: 2022-11-14 00:13:44.715352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c3308ba315'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'item',
        sa.Column('iditem', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('amount', sa.Integer(), nullable=True),
        sa.Column('price', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=255), nullable=False),
        sa.Column('category', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=False),
        sa.Column('image', sa.String(length=255)),
        sa.PrimaryKeyConstraint('iditem')
    )
    op.create_table(
        'user',
        sa.Column('iduser', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('username', sa.String(length=255), nullable=False),
        sa.Column('firstname', sa.String(length=255), nullable=False),
        sa.Column('lastname', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('phone', sa.String(length=255), nullable=False),
        sa.Column('is_admin', sa.Boolean(False)),
        sa.PrimaryKeyConstraint('iduser')
    )
    op.create_table(
        'order',
        sa.Column('idorder', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('quantity', sa.Integer(), nullable=True),
        sa.Column('address', sa.String(length=255), nullable=False),
        sa.Column('cost', sa.Integer(), nullable=True),
        sa.Column('message', sa.String(length=500)),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('item_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['item_id'], ['item.iditem'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.iduser'], ),
        sa.PrimaryKeyConstraint('idorder')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('user')
    op.drop_table('item')
    # ### end Alembic commands ###
